name : CI Pipeline

on : 
  push :
    branches :
      - main

jobs :
  build:
    runs-on: ubuntu-latest

   steps:
   -name: Checkout code
    uses: actions/checkout@v3

   -name: Set up Phyton
    uses: actions/setup-phyton@v4
    with:
      phyton-version: '3.9'

   -name: Install dependencies
    run: |
      phyton -m pip install --upgrade pip
      pip install -r requirements.txt

   -name: run application 
    run: phyton app.py
